Feat/datepicker simple filter
B3Partners/tailormap-legacy pull request #1022
Opened 2018-04-25 11:51 UTC by mtoonen

2018-04-25 12:06 UTC, mprins requested changes
I don't like the reformatting of the context file

2018-04-25 12:06 UTC, mprins commented on viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/FeatureSource.java
> +            org.geotools.data.Query q = new org.geotools.data.Query(sft.getTypeName(), f);
I think this should use an import statement for Query, also on line 171

2018-04-25 12:36 UTC, mtoonen commented on viewer-config-persistence/src/main/java/nl/b3p/viewer/config/services/FeatureSource.java
> +            org.geotools.data.Query q = new org.geotools.data.Query(sft.getTypeName(), f);
Necessary because of import java.persistence.* (which also has a Query class)

2018-04-26 08:04 UTC, mprins approved these changes

2018-04-26 08:11 UTC, merged