Feat/upload documents
B3Partners/tailormap-legacy pull request #1075
Opened 2018-06-06 08:13 UTC by mtoonen

2018-06-06 13:03 UTC, mtoonen commented
@mprins Weet jij waarom de closure-compiler-maven-plugin het niet doet? Ik zie hem wel in de central repo staan...

2018-06-06 14:32 UTC, mprins commented on viewer-admin/src/main/webapp/WEB-INF/jsp/application/applicationTreeLayer.jsp
> +            <script type="text/javascript" src="${contextPath}/resources/js/application/applicationTreeLayer.js?123"></script>
waarom? 123?

2018-06-06 14:36 UTC, mprins commented on viewer/pom.xml
> +                                <param>${viewerhtml.path}/common/ajax/File.js</param>
zit deze file er wel in? zie 'm niet in deze PR, dat zou een probleem zijn voor de closure compiler

2018-06-06 14:38 UTC, mprins commented on viewer/pom.xml
> +                                <param>${viewerhtml.path}/common/ajax/File.js</param>
ik zie `File.js` niet... 💣

2018-06-07 08:14 UTC, mprins requested changes
- remove the ?123

- I think we should make the max upload size explicit instead of relying on whatever the default is in the tomcat instance at hand. I think 5Mb is a good value to start, seeing as many devices take hi-res pictures nowadays

2018-06-07 11:51 UTC, mtoonen commented
Stripes' default for filesize is 10mb, so that should be enough.

2018-06-07 12:35 UTC, mprins approved these changes

2018-06-07 13:39 UTC, merged