First working version of the external link opener
B3Partners/tailormap-legacy pull request #1101
Opened 2018-06-21 12:21 UTC by mtoonen

New component. Provides the ability to create links with some mapvariables. Links are accessible via the right mouse button.

2018-06-21 16:39 UTC, mprins requested changes
It seems to be missing the svg icons, also I don't think the context.xml changes are more than whitespace?...

2018-06-21 16:44 UTC, mprins commented on viewer/src/main/webapp/viewer-html/components/ExternalLinks.js
> +            X: coord.x,
we may want to round these values to realistic values, eg. 1/10th meter and or 1/1000th degrees

2018-06-25 07:57 UTC, mtoonen commented
No svg's were used, context.xml didn't change (only a bit more readable)

2018-06-25 08:56 UTC, mprins approved these changes

2018-06-25 09:06 UTC, merged