Refresh feature info after editing feature
B3Partners/tailormap-legacy pull request #1121
Opened 2018-06-29 15:12 UTC by geertplaisier

Solution for  #1115

2018-06-29 20:23 UTC, mprins reviewed
does this also work when a feature is deleted? (need to check)

2018-06-29 20:23 UTC, mprins commented on viewer/src/main/webapp/viewer-html/components/ExtendedFeatureInfo.js
> +        this.config.viewerController.addListener(viewer.viewercontroller.controller.Event.ON_EDIT_SUCCESS, this.featureEdited, this);
odd to use `this.config.viewerController` here while bove we use `this.getViewerController()`

2018-06-29 20:23 UTC, mprins commented on viewer/src/main/webapp/viewer-html/components/FeatureInfo.js
> +        this.config.viewerController.addListener(viewer.viewercontroller.controller.Event.ON_EDIT_SUCCESS, this.featureEdited, this);
odd to use `this.config.viewerController` here while bove we use `this.getViewerController()`

2018-06-29 20:23 UTC, mprins commented
needs backport to 5.2.x branch

2018-07-03 14:11 UTC, mprins commented
I've rebased to current master and force-pushed this

2018-07-03 15:47 UTC, mprins commented
I tested this and it works for attribute edits, but fails to update the extended feature panel  when a feature is deleted.

When a feature is deleted the panel should be erased and the marker should be removed from the map

2018-07-03 15:48 UTC, mprins requested changes
it should also work when features are deleted, see other comments

2018-07-13 10:04 UTC, mtoonen approved these changes

2018-07-24 20:57 UTC, mprins approved these changes

2018-07-24 21:37 UTC, merged