Set the color that has been set in the combineImageSettings otherwise…
B3Partners/tailormap-legacy pull request #1259
Opened 2018-11-07 11:03 UTC by mvdstruijk

… color is always red

2018-11-07 12:10 UTC, mprins approved these changes

2018-11-07 15:10 UTC, mtoonen commented
Don't think this is entirely correct. FeatureStyle _should_ have the correct color. This error is probably a result that the buffercomponent isn't compatible with the (newly implemented) FeatureStyle class.
So I think the buffercomponent should set the color correctly. You can look at the https://github.com/flamingo-geocms/flamingo/tree/feat/extendDrawingCapabilities branch. There i did some adjustments for the drawing component to be completely compatible with the FeatureStyle class

2018-11-07 15:10 UTC, mtoonen requested changes
Don't think this is entirely correct. FeatureStyle should have the correct color. This error is probably a result that the buffercomponent isn't compatible with the (newly implemented) FeatureStyle class.
So I think the buffercomponent should set the color correctly. You can look at the https://github.com/flamingo-geocms/flamingo/tree/feat/extendDrawingCapabilities branch. There i did some adjustments for the drawing component to be completely compatible with the FeatureStyle class

2018-12-17 08:05 UTC, mtoonen approved these changes

2018-12-17 08:06 UTC, merged