Backend api for safetymaps components
B3Partners/tailormap-legacy pull request #2139
Opened 2020-11-30 09:11 UTC by mvdstruijk

2020-11-30 10:59 UTC, mtoonen commented
Waarom niet direct de safetymaps webapp aanroepen? draait die op een ander domein?

2020-12-01 08:40 UTC, mprins requested changes

2020-12-01 08:40 UTC, mprins commented on pom.xml
> +                <version>1.0-SNAPSHOT</version>
er moet een release versie in dependencyManagement gebruikt worden, anders kun je geen release van TM maken

2020-12-03 17:19 UTC, mprins approved these changes

2020-12-08 10:00 UTC, merged