Feat/gbiw 249 meer filtertypes
B3Partners/tailormap-legacy pull request #2189
Opened 2020-12-22 17:33 UTC by RinkeHeida

2020-12-23 10:58 UTC, mtoonen commented
- [ ] Branch was niet up to date met feat/gbi-component
- [ ] alleen unieke waardes filteren werkt, rest niet
- [ ] blijft een soort selectie/klik ripple staan bij openen die pas weggaat bij klikken (zie afbeelding)
![Screenshot from 2020-12-23 11-56-52](https://user-images.githubusercontent.com/1853172/102989532-0d51e500-4516-11eb-8cda-13ac3b7bd872.png)

2020-12-23 11:10 UTC, RinkeHeida commented
Hij was wel up-to-date en werkend voor alle 3 filters, maar mogelijk is er ondertussen nog een wijziging geweest.

2020-12-23 11:25 UTC, RinkeHeida commented
Ik heb net een pull van feat/gbi-component gedaan en gemerged met 249 -> dan werkt alles nog steeds bij mij.
Heb je mogelijk ook al een andere branch ingeladen?

2020-12-23 14:04 UTC, mtoonen commented
Het werd me al duidelijk: je had twee branches die qua naam bijna hetzelfde waren: RinkeHeida:feat/GBIW-249_meer_filtertypes en RinkeHeida:feat/GBIW-249_meerdere_filtertypes: die laatste deed het niet

2020-12-23 14:08 UTC, RinkeHeida commented
Maar GBIW-249_meerdere_filtertypes had ik toch niet PR gedaan??? Dat was een eerste poging die ik heb laten vervallen (zal ik ook verwijderen.
Ik kom nog met een kleine update op GBIW-249 binnen nu en snel.

2020-12-23 14:14 UTC, RinkeHeida commented
Laatste wijziging heb ik verwerkt.

2020-12-24 07:49 UTC, mtoonen requested changes

2020-12-24 07:49 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  }
Is er een reden dat je dit hier implementeerd ipv de attributelist-filter een ColumnController te geven?

Voelt gek om de call zo door te geven. De datasource is ook niet verantwoordelijk hiervoor, dus moet de publieke api ervan dit ook niet aanbieden

2020-12-24 07:49 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="NOT_LIKE">Waarde bevat niet</mat-radio-button><br/>
Volgens mij zorgt die <br/> voor een hoop ruimte die niet erg nuttig is

2020-12-24 07:49 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="LIKE">Waarde bevat</mat-radio-button><br/>
br kan denk ik weg?

2020-12-24 09:33 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="NOT_LIKE">Waarde bevat niet</mat-radio-button><br/>
Heeft dit betrekking op de <br/>?

2020-12-24 09:48 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="LIKE">Waarde bevat</mat-radio-button><br/>
Als ik die weghaal staan de radio's achterelkaar.
Heb geprobeerd met mat-radio-group  fxLayout="column" en ook css

2020-12-24 09:55 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="NOT_LIKE">Waarde bevat niet</mat-radio-button><br/>
O, ja... github maakte van de < b r /> een newline :-D

2020-12-24 09:56 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="LIKE">Waarde bevat</mat-radio-button><br/>
Hmm, ok, iets voor later

2020-12-24 09:56 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-filter-values-form/attributelist-filter-values-form.component.html
> +    <mat-radio-button value="NOT_LIKE">Waarde bevat niet</mat-radio-button><br/>
Er wordt wel ergens veel ruimte gepakt als het input field komt, maar daar ben ik al mee aan het stoeien geweest om dat kleiner te krijgen.

2020-12-24 10:45 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  }
In attributelist-table.component gebeurd ook al iets dergelijks: 
  public getActiveColumns(includeSpecial: boolean): AttributelistColumn[] {
    return this.dataSource.columnController.getActiveColumns(includeSpecial);
  }
Vandaar dat ik het zo opgelost heb denk ik, want als atributelist-filter de columncontroller moet krijgen dan moet attributelist-table dat ook.

2020-12-24 11:14 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  }
Als ik in de constructor van attributelist-filter AttributelistColumnController opneem blijft ie leeg.
Is wel op te lossen door in setFilter de columnController uit de parameter te halen, maar weet niet zeker of dat wel de juiste route is.

2020-12-24 11:29 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  }
Ik haal de columnController nu uit de aanroep van setFilter

2020-12-24 12:00 UTC, mtoonen commented
Bij het sluiten van de filterdialog via escape krijg je een fout: core.js:4197 ERROR TypeError: Cannot read property 'filterSetting' of undefined
    at SafeSubscriber._next (attributelist-filter.ts:138)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.next (Subscriber.ts:207)
    at Subscriber._next (Subscriber.ts:139)
    at Subscriber.next (Subscriber.ts:99)
    at Subject.next (Subject.ts:70)

2020-12-24 12:04 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  }
attributelist-filter is een class die je zelf aanmaakt, en niet wordt geinject. Dus als je hem in de contructor opneemt, moet je hem daar ook meegeven ;)

2020-12-24 12:08 UTC, mtoonen requested changes

2020-12-24 12:08 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  // }
Kan gewoon weg

2020-12-24 12:08 UTC, mtoonen commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
> +          if (filterDialogSettings.filterSetting !== 'CANCEL') {
Levert fout op bij het sluiten via escape toets.

2020-12-24 12:41 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-datasource.ts
> +  // }
Klopt, dacht dat ik die al opgeruimd had.

2020-12-24 12:47 UTC, RinkeHeida commented on tailormap-components/projects/core/src/lib/user-interface/attributelist/attributelist-common/attributelist-filter.ts
> +          if (filterDialogSettings.filterSetting !== 'CANCEL') {
Goed gevonden!
heb ik nu afgevangen.

2020-12-24 12:51 UTC, mtoonen approved these changes

2020-12-24 13:01 UTC, merged