Refactor/make viewer config persistence dumber
B3Partners/tailormap-legacy pull request #2573
Opened 2021-04-02 10:10 UTC by mtoonen

2021-04-02 12:18 UTC, matthijsln commented
looks good

2021-04-08 10:17 UTC, mtoonen commented
Codecov doesn't seem to see unittestcoverage from viewer-config-persistence-helpers?

2021-04-08 12:48 UTC, mprins requested changes
Paar kleine opmerkingen. 
Verder denk ik dat de database driver exclusions van de geotools modules beter in de `dependencyManagment` sectie van de hoofd pom kunnen worden opgenomen (en daarmee centraal gemanaged worden)

2021-04-08 12:48 UTC, mprins commented on viewer-config-persistence-helpers/pom.xml
> +                <groupId>org.apache.maven.plugins</groupId>
deze groupId is de default dus kun je weg laten
```suggestion
```

2021-04-08 12:48 UTC, mprins commented on viewer-config-persistence-helpers/pom.xml
> +                </exclusion>
We gebruiken geen jtds maar mssql-jdbc, en in geotools is volgens mij jtds ook niet als include opgenomen, iig ook mssql-jdbc uitsluiten.

```suggestion
                </exclusion>
                <exclusion>
                    <groupId>com.microsoft.sqlserver</groupId>
                    <artifactId>mssql-jdbc</artifactId>
                </exclusion>
```

2021-04-08 12:48 UTC, mprins commented on viewer-commons/src/test/java/nl/b3p/mail/MailerTest.java
> +            assert (true);
tamelijk zinloze testcase..., kan je net zo goed MailerTest helemaal weggooien

2021-04-09 12:15 UTC, matthijsln approved these changes

2021-04-09 12:49 UTC, mprins approved these changes

2021-04-13 08:57 UTC, mprins commented
ik denk dat deze gemerged kan worden?

2021-04-15 08:45 UTC, mprins commented on viewer-config-persistence/src/main/resources/META-INF/persistence.xml
> -            <property name="hibernate.ejb.naming_strategy" value="org.hibernate.cfg.ImprovedNamingStrategy"/>
maakt de build stuk...

```
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.codehaus.mojo:hibernate3-maven-plugin:3.0:run (schema-export) on project viewer-config-persistence: There was an error creating the AntRun task. An Ant BuildException has occured: Problems in creating a configuration for JPA. Have you remembered to add hibernate EntityManager jars to the classpath ?: InvocationTargetException: [PersistenceUnit: viewer-config-oracle] Unable to configure EntityManagerFactory: Unable to create unique key constraint (code, application) on table Bookmark: application not found -> [Help 1]
```

2021-05-11 15:21 UTC, mprins commented
@mtoonen Ik denk dat deze is ingehaald door #2670 en dus gesloten kan worden?

2021-05-12 07:53 UTC, closed without merging