TM-35: Show message for creating userlayer from userlayer, this is not valid
B3Partners/tailormap-legacy pull request #2644
Opened 2021-04-20 09:00 UTC by mvdstruijk

https://b3partners.atlassian.net/jira/software/projects/TM/boards/14?selectedIssue=TM-35

2021-04-20 13:47 UTC, mtoonen requested changes
Ik denk dat het mooier is om uit te grijzen (met een tooltip die deze uitleg geeft)

2021-04-20 14:15 UTC, mvdstruijk commented
> Ik denk dat het mooier is om uit te grijzen (met een tooltip die deze uitleg geeft)

2021-04-21 07:31 UTC, mtoonen approved these changes

2021-04-21 08:39 UTC, geertplaisier approved these changes

2021-04-21 08:40 UTC, mtoonen approved these changes

2021-04-21 08:41 UTC, merged