TM-11: use css variable for multiple columns in passport
B3Partners/tailormap-legacy pull request #2662
Opened 2021-04-22 13:07 UTC by mvdstruijk

Fixes TM-11

2021-04-22 13:16 UTC, mtoonen approved these changes
Seems to work :+1:

2021-04-23 08:11 UTC, geertplaisier requested changes

2021-04-23 08:11 UTC, geertplaisier commented on tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
> +  float: left;
Maybe better to use a display: flex parent & set flex: 1 on the tabs. Floating can break your layout quite easily and then you also don't need to set a width

2021-04-23 08:11 UTC, geertplaisier commented on tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.css
> +  height: 77px;
Why is this needed?

2021-04-23 08:11 UTC, geertplaisier commented on tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.html
> +      <div *ngFor="let column of getColumns()" class="tab">
This is not really efficient and happens on every CD

2021-04-23 08:11 UTC, geertplaisier commented on tailormap-components/projects/core/src/lib/feature-form/form-creator/form-creator.component.ts
> +    document.documentElement.style.setProperty('--overlay-panel-columns', Math.max.apply(Math,this.formConfig.fields.map(field=> field.column)));
I think its more efficient to create a Column model or something. So you only have to create the columns once and you could also add the attributes to this column model so you don't need the getAttributes method below.

2021-04-23 08:11 UTC, geertplaisier commented on tailormap-components/projects/core/src/styles/styles.css
> +  width: calc(var(--overlay-panel-columns) * var(--overlay-panel-width));
Wouldn't do this in the styles.css because they are meant to be global and this is quite specific

2021-04-23 12:56 UTC, geertplaisier approved these changes

2021-04-23 13:12 UTC, merged