Remove bulkedit component
B3Partners/tailormap-legacy pull request #2728
Opened 2021-06-09 08:30 UTC by mtoonen

2021-06-09 09:56 UTC, matthijsln approved these changes

2021-06-10 09:20 UTC, mprins requested changes
Kun je ook de dockerfile etc. voor een geoserver test instantie die met de originele PR zijn binnegekomen opruimen?
zie: https://github.com/B3Partners/tailormap/pull/1464/files

volgens mij kan deze deze hele directory weg: https://github.com/B3Partners/tailormap/tree/master/viewer-commons/docker

en dan in de CI het aanzwengelen van geoserver uit zetten, want die wordt nergens andere gebruikt volgens mij: 
https://github.com/B3Partners/tailormap/blob/af1537315d7e5bbd8493953da7b02681ecd41fcc/.github/workflows/ubuntu-maven.yml#L45-L49


en dependabot config:
https://github.com/B3Partners/tailormap/blob/af1537315d7e5bbd8493953da7b02681ecd41fcc/.github/dependabot.yml#L3-L17

2021-06-11 12:22 UTC, mtoonen commented
> Kun je ook de dockerfile etc. voor een geoserver test instantie die met de originele PR zijn binnegekomen opruimen?
> zie: https://github.com/B3Partners/tailormap/pull/1464/files
> 
> volgens mij kan deze deze hele directory weg: https://github.com/B3Partners/tailormap/tree/master/viewer-commons/docker
> 
> en dan in de CI het aanzwengelen van geoserver uit zetten, want die wordt nergens andere gebruikt volgens mij:
> https://github.com/B3Partners/tailormap/blob/af1537315d7e5bbd8493953da7b02681ecd41fcc/.github/workflows/ubuntu-maven.yml#L45-L49
> 
> en dependabot config:
> https://github.com/B3Partners/tailormap/blob/af1537315d7e5bbd8493953da7b02681ecd41fcc/.github/dependabot.yml#L3-L17

Good catch! Done

2021-06-11 13:12 UTC, mprins approved these changes

2021-06-11 14:43 UTC, merged