Use tomcat's LockOutRealm to prevent brute-force / dictionary attacks
B3Partners/tailormap-legacy pull request #727
Opened 2016-12-08 10:58 UTC by mprins

close #726

2016-12-08 16:42 UTC, mprins commented
Currently the actual testcase for the viewer-admin is ignored because there is a problem setting up the jndi authentication realm from within the tomcat7-maven-plugin that I can't figure out.

2016-12-09 07:45 UTC, mtoonen reviewed
Wow, this looks REALLY good!!1!

2016-12-09 07:47 UTC, mtoonen requested changes
Make the jndi work for the authentication realm, minion!

2016-12-09 08:05 UTC, mtoonen approved these changes

2016-12-09 08:05 UTC, merged

2016-12-09 08:05 UTC, mtoonen commented
It's amazing, Mark!